name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run RAG integration test
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        run: |
          # Create temporary files for API keys
          echo "$OPENAI_API_KEY" > /tmp/openai_key
          echo "$CLAUDE_API_KEY" > /tmp/claude_key
          # Set environment variables to point to the files
          export OPENAI_API_KEY=/tmp/openai_key
          export CLAUDE_API_KEY=/tmp/claude_key
          # Run tests
          python -m unittest discover -s tests -p "test_*.py"
          # Clean up
          rm /tmp/openai_key /tmp/claude_key



